#!/bin/bash

main(){
  readonly media_convert_directory=$(get_media_convert_directory "${MEDIA_TYPE}")
  readonly media_import_directory=$(get_media_import_directory "${MEDIA_TYPE}")
  readonly mkv_media_log="${mkvlog}${MEDIA_TYPE,,}.log"
  readonly mp4_media_log="${mp4log}${MEDIA_TYPE,,}.log"
  readonly failed_media_log="${failedlog}${MEDIA_TYPE,,}.log"
  readonly media_handbrake_log="${handbrake_log}${MEDIA_TYPE,,}.log"
  # Remove previous "output" file since it's an incomplete conversion from container shutdown
  if [[ $(find "${media_convert_directory}" -newermt $(date +%Y-%m-%d -d '20 year ago') -type f) ]]; then
    local -r input_file=$(ls -1t "${media_convert_directory}"|head -1)
  else
    exit 0
  fi
  local -r input_extension="${input_file^^}"
  if [[ "${input_extension: -4}" == ".MKV" ]]; then
    convert_mkv "${input_file}" "${media_convert_directory}"
  else
    convert_handbrake "${input_file}" "${media_convert_directory}" "${media_import_directory}"
  fi
  exit 0
}

source /opt/functions

MEDIA_SERVER="${1}"
ENCODE="${2}"
MEDIA_TYPE="${3}"

# Set niceness (Priority) of conversion process
declare -r nice_level=$(set_priority "${MEDIA_SERVER}")

main
