#!/bin/bash

################################################################################
# Variables                                                                    #
################################################################################

# Set PATH
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Location for failed media conversion files
failed_dir="/media/FAILED"

# Location to create log file
log_dir="/media/log"
log="${log_dir}/media-converter.log"

# Location to check for new media files
movie_add="/media/Complete/Movies"
tv_add="/media/Complete/TVShows"

# Location to move media files to for conversion
movie_convert="/media/Complete/Convert/Movies"
tv_convert="/media/Complete/Convert/TVShows"

# Location to move media files to for ingestion by SickChill, CoachPotato, etc
movie_import="/media/Complete/IMPORT/Movies"
tv_import="/media/Complete/IMPORT/TVShows"

# Location of binaries used by container
handbrake=/usr/local/bin/HandBrakeCLI
ffmpeg=/usr/local/bin/ffmpeg
mediainfo=/usr/bin/mediainfo

# Set colors for status message
red='\e[1;31m'
yellow='\e[1;33m'
green='\e[1;32m'
white='\e[1;97m'
clear='\e[0m'

################################################################################
# Functions                                                                    #
################################################################################

# Exit function when script misbehaves
die(){
  print_info "Fail point: ${BASH_SOURCE[1]}: line ${BASH_LINENO[0]}: ${FUNCNAME[1]}" >&2
  exit 1
}

# Create status messages
print_error(){ echo -e "${red}[ERROR]: ${1}${clear}"|tee -a ${log}; }
print_warning(){ echo -e "${yellow}[WARNING]: ${1}${clear}"|tee -a ${log}; }
print_info(){ echo -e "${white}${1}${clear}"|tee -a ${log}; }
print_ok(){ echo -e "${green}[OK]: ${1}${clear}"|tee -a ${log}; }

# Set mod time of dummyfile so we can generate uptime for container
container_uptime(){
  touch /var/tmp/.media-converter.uptime
}

# Add "media" user and group, and map them to provided UID/GID or 1000 if not provided
add_user(){
  groupadd -g "${2}" media
  useradd -s /bin/bash -m -u "${1}" -g media media
  print_info "\"media\" user is mapped to external UID $(id -u media)"
  print_info "\"media\" group is mapped to external GID $(id -g media)"
}

# Set timezone inside container for logfile entries
set_timezone(){
  echo "${TZ}"|tee /etc/timezone
  dpkg-reconfigure -f noninteractive tzdata > /dev/null 2>&1
  print_info "Timezone set to ${TZ}"
  print_info "Current date and time inside container: $(date +%b-%d" "%H:%M)"
}

# Setup logfile
setup_logfile(){
  if [[ ! -f "${log}" ]]; then
    echo " Type   | Input     | Converted | Encoder | Time      | Filename" >> "${log}"
  fi
  chown media:media "${log}" || die
}

# Check if /media is mounted to an external volume and writeable by media user
check_mount(){
  if ! mountpoint /media; then
    print_error "\"/media\" NOT mounted to external volume"
    die
  fi
}

# Create directory passed to function and set ownership to \"media\" user"
create_directory(){
  if [[ -d "${1}" ]]; then
    directory_writeable "${1}"
  else
    if [[ $(mkdir -p "${1}") ]]; then
      print_ok "Created ${1}"
    fi
    if [[ ! $(chown media:media "${1}") ]]; then
      print_error "Unable to set ownership of ${1} to UID ${PUID}"
      die
    fi
  fi
}

# Print niceness level for logfile
print_priority_info(){
  if [[ ${MEDIA_SERVER} == "no" ]]; then
    print_info "\"MEDIA_SERVER\" variable set to ${MEDIA_SERVR}, leaving default niceness for converter functions"
  else
    print_info "\"MEDIA_SERVER\" variable set to ${MEDIA_SERVER}, lowering niceness for converter functions"
  fi
}

# Set niceness level of encoder actions
set_priority(){
  if [[ ${1} == "no" ]]; then
    nice_level='-0'
  else
    nice_level='-15'
  fi
  echo "${nice_level}"
}

# Check if directory passed to function is writeable by \"media\" user"
directory_writeable(){
  sudo -u media bash -c "source /opt/functions && if [[ ! -w \"${1}\" ]]; then \
                           print_error \"${1} not writeable by UID ${PUID}\"; \
                           die; \
                        fi"
}

move_media(){
  # This ignores any files that might be sample media files (TV shows under 50MB in size and Movies under 500MB)
  find "${tv_add}" -type f -not -name '*sample*' -size +50M -regex '.*\.\(avi\|mod\|mpg\|mp4\|m4v\|mkv\)' -exec mv {} "${tv_convert}" \;
  find "${movie_add}" -type f -not -name '*sample*' -size +500M -regex '.*\.\(avi\|mod\|mpg\|mp4\|m4v\|mkv\)' -exec mv {} "${movie_convert}" \;
  # Remove left behind files older than 2 days
  find "${tv_add}/" -ctime +2 -exec rm -rf {} +
  find "${movie_add}/" -ctime +2 -exec rm -rf {} +
}
