#!/bin/bash

container_setup(){
  echo "${ENCODE}" > /tmp/ENCODE
  chmod 444 /tmp/ENCODE
  echo "${MEDIA_SERVER}" > /tmp/MEDIA_SERVER
  chmod 444 /tmp/MEDIA_SERVER
  echo "${GROWL}:${GROWL_IP}:${GROWL_PORT}" > /tmp/GROWL
  chmod 444 /tmp/GROWL
  source /opt/functions
  set_timezone ${TZ}
  add_user ${PUID} ${PGID}
  touch ${log} && chown media:media ${log}
  chown -R media:media /log
  check_mount || exit 1
  for directory in Complete Download Logs; do
    create_directory /media/${directory} || exit 1
  done
  for directory in /media/Complete /media/Download /media/Complete/Convert /media/Complete/IMPORT; do
    for media_directory in TVShows Movies; do
      create_directory ${directory}/${media_directory} || exit 1
    done
  done
  container_creation_date
  log_priority
  if [[ ! -f /media/Logs/converted.log ]]; then
    echo " Type   | Input     | Converted | Encoder | Time      | Filename" >> /media/Logs/converted.log
  fi
}


container_setup
touch /var/tmp/.media-converter.uptime
while true; do
  sudo -u media bash -c "source /opt/functions;move_media"; \
  sudo -u media bash -c "source /opt/functions;set_priority;convert_media /media/Complete/Convert/TVShows"; \
  sudo -u media bash -c "source /opt/functions;set_priority;convert_media /media/Complete/Convert/Movies"; \
  sleep 60
done

