#!/bin/bash

source /opt/functions
export PUID=${PUID}
export PGID=${PGID}
export TZ=${TZ}
export ENCODE=${ENCODE}
export MEDIA_SERVER=${MEDIA_SERVER}

container_setup(){
  add_user "${PUID}" "${PGID}"
  set_timezone "${TZ}"
  check_mount
  for directory in failed_dir log_dir media_base movie_add tv_add movie_convert tv_convert movie_import tv_import; do
    create_directory "${!directory}"
  done
  setup_logfile
  nohup bash -c 'touch /var/tmp/.media-converter.uptime'
  print_priority_info
}

media_converter_loop(){
  while true; do
    sudo -u media bash -c "source /opt/functions; move_media"; \
    sudo -u media bash -c "/opt/convert_media \"${MEDIA_SERVER}\" \"${ENCODE}\" \"MOVIE\""; \
    sudo -u media bash -c "/opt/convert_media \"${MEDIA_SERVER}\" \"${ENCODE}\" \"TV\""; \
    sleep 60
  done
}

main(){
  container_setup
  media_converter_loop
}

main
