#!/bin/bash

main(){
  clear
  get_container_uptime
  echo -e "\e[1;97mContainer created: $(date -d @$(stat -c %Y /var/tmp/.media-converter.create) "+%b-%d-%Y %H:%M")"
  echo -e "Container uptime: ${container_uptime}\n"
  check_space "/media"
  declare -i tv_count=$(ls -1 "${tv_convert}" | egrep -v "-converted.mp4|.srt")
  declare -i movie_count=$(ls -1 "${movie_convert}" | egrep -v "-converted.mp4|.srt")
  print_info_no_log "\n$(tv_grammar ${tv_count}) waiting to be encoded"
  print_info_no_log "$(movie_grammar ${movie_count}) waiting to be encoded\n"
  [[ $(pgrep ffmpeg) ]] && print_notice_no_log "FFMPEG is running"
  if [[ $(pgrep HandBrakeCLI) ]]; then
    print_notice_no_log "HandBrake is converting:\n$(ps -ef|grep -o "\-\-output.*"|sed -e 's/\-\-output \/media\/Complete\/Convert\/.*\///' -e 's/\-converted\.mp4//')"
  else
    print_notice_no_log "No current encode jobs running"
  fi
}

source /opt/functions

main
